const actionTypes = {
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    SET_GAMES: 'SET_GAMES',
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_POPUP_VIEW: 'SET_POPUP_VIEW',
    SET_LOADING: 'SET_LOADING',
    // ADD_FAVORITE_MOVIE: 'ADD_FAVORITE_MOVIE',
    // REMOVE_FAVORITE_MOVIE: 'REMOVE_FAVORITE_MOVIE',
    // SET_FAVORITE_MOVIES: 'SET_FAVORITE_MOVIES',
}

export default actionTypes;